version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn war:war
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/order-service.war
  discard-paths: yes
